Vagrant.configure("2") do |config|
	config.vm.define "abel-mqaS" do |s|
		s.vm.box = "bento/debian-11"
		s.vm.hostname = "abel-mqaS"
		s.vm.network "private_network", ip: "192.168.56.110"
		s.vm.provider "vmware_desktop" do |vb|
			vb.memory = 1024
			vb.cpus = 1
		end
		s.vm.provision "shell", path: "scripts/server.sh"
	end
end
